name: CI

on:
    push:
        tags: [ "*.*.*" ]

jobs:
    build-and-publish:
        runs-on: ubuntu-latest
        permissions:
            contents: read
        steps:
            -   uses: actions/checkout@v4

            -   uses: oven-sh/setup-bun@v2

            -   run: bun install

            -   run: tsc --noEmit

            -   run: bun test

            -   run: bun run build

            -   run: bun publish --access public
                env:
                    NPM_CONFIG_TOKEN: ${{ secrets.NPM_TOKEN }}